version: '3.8'

services:
  frontend:
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DATABASE_URL=sqlite:///app/data/ajsender.sqlite
      - WHATSAPP_SESSION_PATH=/app/whatsapp-session
      - CORS_ORIGIN=https://sender.ajricardo.com
      - LOG_LEVEL=info
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    volumes:
      - ./whatsapp-session:/app/whatsapp-session:rw
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw

  caddy:
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./logs/caddy:/var/log/caddy:rw
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: false
  caddy_config:
    external: false

networks:
  ajsender-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
