version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - ajsender-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - WHATSAPP_AUTH_URL=http://whatsapp-server:3002
      - DATABASE_URL=sqlite:///app/data/database.sqlite
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - whatsapp-server
    networks:
      - ajsender-network
    restart: unless-stopped

  whatsapp-server:
    build:
      context: ./whatsapp-server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
    volumes:
      - ./whatsapp-sessions:/app/.wwebjs_auth
      - ./whatsapp-cache:/app/.wwebjs_cache
      - ./whatsapp-public:/app/public
    networks:
      - ajsender-network
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ajsender-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:

networks:
  ajsender-network:
    driver: bridge
